{"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"kind":"text","text":": "},{"text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"SotoCore"}],"title":"context"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"abstract":[{"text":"additional context information related to the error","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/context"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","kind":"typeIdentifier","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}]}],"kind":"symbol","references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","role":"collection","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","kind":"symbol","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"url":"\/documentation\/sotocore","title":"SotoCore"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"type":"topic","title":"AWSServerError","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSServerError"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","url":"\/documentation\/sotocore\/awsservererror","navigatorTitle":[{"kind":"identifier","text":"AWSServerError"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"title":"context","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"additional context information related to the error"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/sotocore\/awsservererror\/context"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","title":"AWSErrorContext","url":"\/documentation\/sotocore\/awserrorcontext","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWSErrorContext"}],"navigatorTitle":[{"text":"AWSErrorContext","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Additional information about error"}],"kind":"symbol"}}}