{"abstract":[{"text":"additional context information related to the error","type":"text"}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"modules":[{"name":"SotoCore"}],"title":"context","role":"symbol"},"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sotocore\/awsservererror\/context"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier","text":"AWSErrorContext","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext"},{"text":"?","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"kind":"symbol","type":"topic","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","abstract":[{"type":"text","text":"additional context information related to the error"}],"url":"\/documentation\/sotocore\/awsservererror\/context","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":"?"}],"title":"context","role":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore":{"abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","title":"SotoCore","url":"\/documentation\/sotocore","role":"collection","type":"topic"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSErrorContext","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","abstract":[{"text":"Additional information about error","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"title":"AWSErrorContext","url":"\/documentation\/sotocore\/awserrorcontext"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"kind":"symbol","url":"\/documentation\/sotocore\/awsservererror","navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}],"title":"AWSServerError","abstract":[],"role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWSServerError","kind":"identifier"}],"type":"topic"}}}