{"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalFailure","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSServerError","preciseIdentifier":"s:8SotoCore14AWSServerErrorV","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"SotoCore"}],"roleHeading":"Type Property","title":"internalFailure","externalID":"s:8SotoCore14AWSServerErrorV15internalFailureACvpZ","role":"symbol"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"internalFailure","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","text":"AWSServerError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/internalfailure"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"abstract":[],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSServerError"}],"navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}],"type":"topic","title":"AWSServerError","url":"\/documentation\/sotocore\/awsservererror"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/internalFailure":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","url":"\/documentation\/sotocore\/awsservererror\/internalfailure","type":"topic","title":"internalFailure","role":"symbol","kind":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","title":"SotoCore","role":"collection"}}}