{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalFailure","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalFailure","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError"}],"externalID":"s:8SotoCore14AWSServerErrorV15internalFailureACvpZ","roleHeading":"Type Property","symbolKind":"property","role":"symbol","title":"internalFailure","modules":[{"name":"SotoCore"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/internalfailure"]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","title":"SotoCore","url":"\/documentation\/sotocore","role":"collection","type":"topic"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/internalFailure":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"text":": ","kind":"text"},{"text":"AWSServerError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"}],"kind":"symbol","url":"\/documentation\/sotocore\/awsservererror\/internalfailure","type":"topic","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","role":"symbol","title":"internalFailure","abstract":[]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"kind":"symbol","url":"\/documentation\/sotocore\/awsservererror","navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}],"title":"AWSServerError","abstract":[],"role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWSServerError","kind":"identifier"}],"type":"topic"}}}