{"abstract":[{"type":"text","text":"additional context information related to the error"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsresponseerror\/context"]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError"]]},"metadata":{"symbolKind":"property","externalID":"s:8SotoCore16AWSResponseErrorV7contextAA15AWSErrorContextVSgvp","modules":[{"name":"SotoCore"}],"roleHeading":"Instance Property","role":"symbol","title":"context","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier","text":"AWSErrorContext"},{"text":"?","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError":{"title":"AWSResponseError","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError","type":"topic","url":"\/documentation\/sotocore\/awsresponseerror","role":"symbol","abstract":[{"type":"text","text":"Response Error type returned by Soto if the error code is unrecognised"}],"navigatorTitle":[{"kind":"identifier","text":"AWSResponseError"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSResponseError","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","title":"SotoCore","role":"collection"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError/context":{"title":"context","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context","type":"topic","url":"\/documentation\/sotocore\/awsresponseerror\/context","role":"symbol","abstract":[{"type":"text","text":"additional context information related to the error"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext"},{"text":"?","kind":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"title":"AWSErrorContext","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","type":"topic","url":"\/documentation\/sotocore\/awserrorcontext","role":"symbol","abstract":[{"type":"text","text":"Additional information about error"}],"navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSErrorContext","kind":"identifier"}]}}}