{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"title":"context","symbolKind":"property","modules":[{"name":"SotoCore"}],"role":"symbol","roleHeading":"Instance Property","externalID":"s:8SotoCore16AWSResponseErrorV7contextAA15AWSErrorContextVSgvp"},"abstract":[{"text":"additional context information related to the error","type":"text"}],"variants":[{"paths":["\/documentation\/sotocore\/awsresponseerror\/context"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier","text":"AWSErrorContext","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext"},{"text":"?","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError"]]},"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","title":"SotoCore","url":"\/documentation\/sotocore","role":"collection","type":"topic"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSResponseError","kind":"identifier"}],"title":"AWSResponseError","navigatorTitle":[{"text":"AWSResponseError","kind":"identifier"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError","url":"\/documentation\/sotocore\/awsresponseerror","kind":"symbol","abstract":[{"type":"text","text":"Response Error type returned by Soto if the error code is unrecognised"}],"type":"topic"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSErrorContext","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","abstract":[{"text":"Additional information about error","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"title":"AWSErrorContext","url":"\/documentation\/sotocore\/awserrorcontext"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError/context":{"title":"context","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"additional context information related to the error"}],"url":"\/documentation\/sotocore\/awsresponseerror\/context","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context","type":"topic"}}}